# Generated by Django 4.2.11 on 2024-03-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nb_service", "0003_service_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="backup_profile",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
