# Generated by Django 4.2.11 on 2024-03-19 10:51

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0060_customlink_button_class"),
        ("nb_service", "0004_alter_service_backup_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="tags",
            field=taggit.managers.TaggableManager(
                through="extras.TaggedItem", to="extras.Tag"
            ),
        ),
    ]
